### ISSUE TITLE
How to extends functionality of any provider?

### ISSUE THREAD

**Issue by githubov** [SocialConnect/auth#100]
I am very new with I success full login with any provide.
but twitter image upload use different api.
I want to extend functionality of Twitter provider class with my custom one without change core file.
if I update SocialConnect/auth feature maybe I lost my customization.
I need help on this.

Thank You.
Great PHP LIB SocialConnect/auth

**Comment by ovr** [comment]
Hey!

I didn't understand nothing, can you clarify what are you trying to reach and where is a problem
You can mention code/examples

Thanks

**Comment by githubov** [comment]
Code are all right I need to add some methods on Provider Twitter class so that it can upload image and make a tweet.

**Comment by ovr** [comment]
I highly recommend creating an external class called service and don't try to create a provider that extends twitter one

Example

```php
<?php

use SocialConnect\OAuth1\AccessToken;
use SocialConnect\OAuth1\Provider\Twitter;

class TwitterService {
    /**
     * @var Twitter
     */
    protected $twitter;

    /**
     * MyAwesomeServiceThatWorksWithTwitter constructor.
     * @param Twitter $twitter
     */
    public function __construct(Twitter $twitter)
    {
        $this->twitter = $twitter;
    }

    public function doSomething(AccessToken $token)
    {
        $this->twitter->request('POST', '/upload', [], $token, [
            'image' => 'heh'
        ]);
    }
}
```

```

**Comment by ovr** [comment]
I am going close this issue because example was provided above and no replies

Thanks
