### ISSUE TITLE
Facebook first_name and last_name are null

### ISSUE THREAD

**Issue by tomaluca95** [SocialConnect/auth#104]
With facebook first_name and last_name are null but using cURL I got values

**Comment by ovr** [comment]
Hey!

What version are you using? Did you specify `first_name` and `last_name` in `identity.fields` inside `options`?

Thanks

**Comment by tomaluca95** [comment]
Thanks, was that!

I have also issues with `birthday`, adding the field in `identity.fields` don't fix that. Can you help me on that?

**Comment by ovr** [comment]
@tomaluca95 Fixed in `3.1.2`, please update

And don't forget that you should specify `birthday` in `identity.fields` + specify `user_birthday` in `scope` (it's needed additional actions in facebook developer site)

Thanks
