### ISSUE TITLE
Steam Provider return User with wrong avatar field

### ISSUE THREAD

**Issue by Ferikl** [SocialConnect/auth#117]
Hey!

Now Steam provider returns `SocialConnect\Common\Entity\User`
with fields: `firstname` and `username`, But Steam response (URL: **'ISteamUser/GetPlayerSummaries/v0002/'**) provides much more information. Like `avatar` and other.

Can you add these **fields** to your User DTO? Or just map correctly `$pictureURL` to Steam `avatar` field.

I suppose its just quick fix in 
`SocialConnect\OpenID\Provider\Steam`
line 78-79 should be something like this:
```
'realname' => 'fullname',
'avatar' => 'pictureURL',
```

Thanks :smiley_cat:

**Comment by ovr** [comment]
Hey! Thanks, fixed.
