### ISSUE TITLE
Read-only subtree package openid-connect is not up-to-date

### ISSUE THREAD

**Issue by Ilyes512** [SocialConnect/auth#120]
Hey,

I was thinking about using this https://github.com/SocialConnect/openid-connect to write my own OpenId Connect provider, but I see it’s not up-to-date with what’s in this main package.

Could it be updated, please? (Hopefully that is automated :)?)

Thanks!

Edit:

I think this might also be the case for it’s dependencies:
```
“socialconnect/provider": "^2.0.0",
"socialconnect/oauth2": "^2.0.0"
```

**Comment by ovr** [comment]
Hello! Wow, forget about this :))

> Hopefully that is automated

Split is automated, but new releases are not

I will do it now

**Comment by ovr** [comment]
Done ✅ 
Check releases, and feel free to close if all is okey

**Comment by ovr** [comment]
ping @Ilyes512
