### ISSUE TITLE
How to get an email from a VK provider?

### ISSUE THREAD

**Issue by dmitrymenshikov** [SocialConnect/auth#132]
Hey! 

How to get email from auth via vk provider? 

The email is not pulled in the \SocialConnect\OAuth2\AccessToken, and the parameters from the "scope" are ignored.

Tnx!

**Comment by ovr** [comment]
Hello @dmitrymenshikov,

It's a bug, after a small research, I found that I removed code inside `Provider\Vk` that store `$email` as protected property and populates it inside `getIdentity` method.

**Comment by dmitrymenshikov** [comment]
@ovr Wonderful! Thank you for your promptness!

**Comment by ovr** [comment]
Fixed/Released in `3.2.1`, please try it and feel free to close this issue.

Thanks

**Comment by dmitrymenshikov** [comment]
All is good. The problem has been resolved.
