### ISSUE TITLE
OpenIdConnect JWT "kid" is not optional for single key keysets.

### ISSUE THREAD

**Issue by MaPePeR** [SocialConnect/auth#139]
Hey!

### Issue

I'm implementing a OpenIDConnect Provider for [Unity IDM](https://www.unity-idm.eu/) and encountered the problem, that the JWT `kid` header attribute is required, even if the `jwks_uri` only returns a single key.

An `InvalidJWT('No kid inside header, but $privateKeyOrSecret specified as JWKSet')`-Exception is thrown.

The [`OpenIDConnect/AbstractProvider::getJWKSet`](https://github.com/SocialConnect/auth/blob/2c13ecf9dd9c32a95e968272904b37a34347fcb2/src/OpenIDConnect/AbstractProvider.php#L39-L61)-Method always returns a `JWKSet`, even though the `JWT::decode` Method only expects a `JWKSet` if there are multiple keys present and a string of the key if there is only one key? (That's the reason i report this against this repo and not SocialConnect/jwx)

### My env

PHP: 7.4.1

Library: SocialConnect/auth

Provider: Provider extending `\SocialConnect\OpenIDConnect\AbstractProvider`

Provider options:

```php
[
    'options' => []
];
```

Thanks :smiley_cat:

**Comment by MaPePeR** [comment]
The easy fix would be:
```patch
--- src/OpenIDConnect/AbstractProvider.php	2020-10-19 14:49:22.000000000 +0200
+++ src/OpenIDConnect/AbstractProvider_.php	2020-10-27 15:18:43.509194414 +0100
@@ -36,7 +36,7 @@
      * @throws InvalidResponse
      * @throws \Psr\Http\Client\ClientExceptionInterface
      */
-    public function getJWKSet(): JWKSet
+    public function getJWKSet()
     {
         $spec = $this->discover();
 
@@ -56,6 +56,10 @@
                 $response
             );
         }
+        
+        if (count($result['keys']) == 1) {
+            return (new JWK($result['keys'][0]))->getPublicKey();
+        }
 
         return new JWKSet($result);
     }
```

But that would be a backwards incompatible fix, because it would break for the case where a `kid` is provided, but only one key is present?

I think the better solution would be to add a method to JWKSet that returns all the keys and allow `kid` to not be set, when there is only one key in the set? But that would have to be changed in SocialConnect/jwx

**Comment by ovr** [comment]
@MaPePeR Sorry for late reply.

I think it's better to override `parseToken` inside your provider.

https://github.com/SocialConnect/auth/blob/2c13ecf9dd9c32a95e968272904b37a34347fcb2/src/OpenIDConnect/AbstractProvider.php#L89

What do you think? Thanks

**Comment by MaPePeR** [comment]
Hi,

thanks for your response.

Overwriting `parseToken` is my workaround at the moment, but for that to work i have to pretty much duplicate the code of the the `AbstractProvider::parseToken` and the code of the `AbstractProvider::getJWKSet` methods in my provider, just to change one function argument:

```php
	public function getJWKSetFixed() { //New Method without typehint, so i can return a single key.
		$spec = $this->discover();

		if (!isset($spec['jwks_uri'])) {
			throw new \RuntimeException('Unknown jwks_uri inside OpenIDConnect specification');
		}

		$response = $this->executeRequest(
			$this->httpStack->createRequest('GET', $spec['jwks_uri'])
		);

		$result = $this->hydrateResponse($response);

		if (!isset($result['keys'])) {
			throw new InvalidResponse(
				'API response without "keys" key inside JSON',
				$response
			);
		}
		if (count($result['keys']) == 1) {
			return (new JWK($result['keys'][0]))->getPublicKey();
		}
		return new JWKSet($result);
	}
	
	/**
	 * {@inheritdoc}
	 */
	public function parseToken(string $body)
	{
		if (empty($body)) {
			throw new InvalidAccessToken('Provider response with empty body');
		}

		$result = json_decode($body, true);
		if ($result) {
			$token = new AccessToken($result);
			$token->setJwt(
				JWT::decode($result['id_token'], $this->getJWKSetFixed(), new DecodeOptions()) //Call different getJWKSet-Method
			);

			return $token;
		}

		throw new InvalidAccessToken('Provider response with not valid JSON');
	}
```

Duplicating code like that is not a very good style, i think. But maybe I'm missing something obvious here that makes this easier?I'm fairly new to this library. Also I think the "fix" above comes with the bug, that a single key, that DOES have a `kid` set is considered invalid.

I think the proper fix is, to allow `JWT` to enumerate the keys in a `JWKSet`, so it can check and validate for the default key, without knowing a `kid`.
The requirement, that the caller of `JWT::decode` has to check if there is a `kid` present or if there is only a single key without a `kid` is bad. I think that should be part of the responsibility of the `JWT` library.

**Comment by ovr** [comment]
I implemented `Countable` interface for `JWKSet`, refs https://github.com/SocialConnect/jwx/commit/d529b459a547a358bddda1460d6ae98d43f0d6e2

I think we should introduce a new method for it, but I am thinking about a name for it.

Maybe `getFirstForOnlyOne` (will throw exception if `count($this->keys) > 0`), what do you think?

After it will be possible to use default implementation for `getJWKSet` because We will be able to move `count($result['keys']) == 1` to `parseToken` method.

cC @ADmad

**Comment by MaPePeR** [comment]
Maybe something like `hasDefault() => count($set) == 1` and `getDefault` that throws if there is no Default.

And then in [`JWT::validateHeaders`](https://github.com/SocialConnect/jwx/blob/d529b459a547a358bddda1460d6ae98d43f0d6e2/src/JWT.php#L177-L185) something like:

```php
        if (isset($this->headers['kid'])) {
            if (!$publicKeyOrSecret instanceof JWKSet) {
                throw new RuntimeException('Please specify jwk set in DecodeOptions, because there is kid inside header');
            }
        } else {
            if ($publicKeyOrSecret instanceof JWKSet && !publicKeyOrSecret->hasDefault()) {
                throw new InvalidJWT('No kid inside header, but $privateKeyOrSecret specified as JWKSet');
            }
        }
```

Something similar would have to be done in [`JWT::verifySignature`](https://github.com/SocialConnect/jwx/blob/d529b459a547a358bddda1460d6ae98d43f0d6e2/src/JWT.php#L271)

**Comment by ADmad** [comment]
Adding new methods `hasDefaultKey(): bool` (which checks if count = 1) and `getDefaultKey()` sounds reasonable to me. `getDefaultKey()` would throw an exception if key count > 1.

**Comment by MaPePeR** [comment]
I created the pull request SocialConnect/jwx#3 to address this.
