### ISSUE TITLE
Slim\App not found

### ISSUE THREAD

**Issue by Det7** [SocialConnect/auth#143]
Hey!

Issue
First time tried setting up SocialConnect. I was following the steps here:
https://socialconnect.lowl.io/installation.html

and got stuck after this:
composer require socialconnect/http-client

as my index.php is getting this error `Fatal error: Uncaught Error: Class 'Slim\App'` not found, in below line:
`$app = new \Slim\App(`

how can I verify if this class is existing?

My env
PHP: 7.3.12 (WAMP)

Library: SocialConnect

Provider: Yahoo

Thanks 😺

**Comment by ovr** [comment]
It's not the SocialConnect class. If you are trying to use `example` inside repository, you should execute `composer install` inside `example` directory.
