### ISSUE TITLE
Update GitLab Provider API Version

### ISSUE THREAD

**Issue by makkus183** [SocialConnect/auth#157]
Hey!

### Issue
The GitLab API V3 is [no longer supported](https://gitlab.com/api/v3/). and returns:

```
{
"error": "API V3 is no longer supported. Use API V4 instead."
}
```
### My env

PHP: `7.4`

Provider: GitLab

Provider options:

Thanks :smiley_cat:

**Comment by ADmad** [comment]
You don't really need to open an issue if you are going to open a PR shortly after :)

**Comment by makkus183** [comment]
Oh ok, sorry :) I thought a PR has to be related to an issue. As you already recognized i am quite new in the contrib business on github :)

**Comment by ADmad** [comment]
No worries, thanks for the PRs.
