### ISSUE TITLE
non proper nbf claim check in JWT.php

### ISSUE THREAD

**Issue by CallumBrankin** [SocialConnect/auth#25]
in /auth/src/OpenIDConnect/JWT.php the nbf claim check doesn't match RFC7519 standards where it says "The processing of the "nbf" claim requires that the current date/time MUST be **after or equal** to the not-before date/time listed in the "nbf" claim.". 

Currently the nbf claim check only checks if the current date/time is **after** the nbf claim. as seen below:

```
if (isset($this->payload->nbf) && $this->payload->nbf > ($propernow)) {
            throw new InvalidJWT(
                'nbf (Not Fefore) claim is not valid '.$nbf.' '. $propernow . ' ' . date(DateTime::RFC3339, $this->payload->nbf)
            );
        }
```

I tried to correct this by changing the operator to **>=** rather than **>** but it doesn't seem to be working correctly. 

This also causes the exception to throw if the auth_time is the same as the nbf claim

**Comment by ovr** [comment]
Hey!

> I tried to correct this by changing the operator to >= rather than > but it doesn't seem to be working correctly.

What was a problem? What provider are you using? (`screw`/`leway`)?

Thanks

**Comment by CallumBrankin** [comment]
I'm using my companies provider called [PixelPin](https://www.pixelpin.co.uk). PixelPin is a passwordless sso that uses pictures instead of password. 

I've successfully implemented PixelPin into your plugin to be used on Zend Framework 3 using [OrgHeiglHybridAuth ](https://github.com/heiglandreas/HybridAuth). 

Currently we're updating our plugins to use OpenID Connect as we will be an OpenID connect provider.

**Comment by ovr** [comment]
I added equal to the `nbf` in https://github.com/SocialConnect/auth/commit/e4da4db4c0b3766cf95314f1fd92154a4388dfa6
As described in issue, I fix this moment -> this is fixedissue
I am going to close this issue

Thanks

**Comment by ovr** [comment]
@CallumBrankin Nope, It was wrong fix, it's not needed to `>=`, I review RFC again when writting tests https://github.com/SocialConnect/auth/pull/30
