### ISSUE TITLE
Validate function in JWT.php doesn't account for time "screw" 

### ISSUE THREAD

**Issue by CallumBrankin** [SocialConnect/auth#26]
Validate function in /auth/src/openidconnect/JWT.php doesn't account for time "screw".

Currently the function gets the current time as 
`$now = time();`
but this doesn't account for time screw, sometimes causing an exception where the auth_time is a single unix time unit before the nbf claim. 

I've corrected this by adding a "proper now" time by adding a single unit to the unix time as shown below:
`$propernow = $now + 1;`
but i believe this isn't the proper way to do it.

**Comment by ovr** [comment]
I think the most proper way should be that `screw`/`leway` should be done on the provider side when they prepare `payload` like

`$time - 20`

but anyway We can add "this hack"

**Comment by CallumBrankin** [comment]
Adding a single unix time unit may not be enough, maybe +2 would make sure it's reliable.

**Comment by ovr** [comment]
Hey @CallumBrankin 
You issue should be fixes now in `master` branch it's (`1.1` release), will be released ASAP
w8thing tests for JWT\JWK

You can try with `dev-master` release

Thanks
