### ISSUE TITLE
socialconnect.lowl.io certificate error

### ISSUE THREAD

**Issue by CallumBrankin** [SocialConnect/auth#27]
When i try to go to socialconnect.lowl.io i get a certificate error.

full error details:

> Session #14595: The server (socialconnect.lowl.io) presented a certificate that did not validate, because it was issued to a different host.

>SANs: dmtry.me, www.dmtry.me, status.dmtry.me, api.dmtry.me, blog.dmtry.me, ab.dmtry.me, wh.dmtry.me, ci.dmtry.me, yt.dmtry.me, resume.dmtry.me, about.dmtry.me, sc.dmtry.me, owl.dmtry.me, phpsa.dmtry.me, en.dmtry.me, socialconnect.dmtry.me, social-connect.dmtry.me, zenti-cp.dmtry.me, zephir.dmtry.me, wiki.dmtry.me, static.phalcon-module.dmtry.me, secret.dmtry.me, docs.dmtry.me, ehealthme.dmtry.me, angular.dmtry.me, pm-react.dmtry.me, react.dmtry.me, pm.dmtry.me, test.dmtry.me, dash.dmtry.me, dashboard.dmtry.me, admin.dmtry.me, docker.dmtry.me, memcached.dmtry.me, mm.dmtry.me, memcache.dmtry.me, pma.dmtry.me
SUBJECT: CN=dmtry.me

**Comment by ovr** [comment]
Just, give me "few" time, I am working on the site for this library
As you can see it's new library :)

**Comment by ovr** [comment]
Moved to https://sc.lowl.io/
