### ISSUE TITLE
Issue with Login on Facebook in-app browser

### ISSUE THREAD

**Issue by trustinbharat** [SocialConnect/auth#31]
Hello there

My web application is coded in Ruby on Rails. The website has a modal "Login/ Sign-up". When the user clicks on "Login-with-Facebook", another page opens up which takes care of Facebook and Twitter Login. After the user is logged-in, the pop-up closes automatically and the user returns to the page of the website as logged-in. Everything works perfectly fine in all browsers. However, when a  user comes to our website on Facebook in-app browser and clicks Login with Facebook on "Login-modal". He is directed to the page where Facebook confirms log-in credentials. After that the page remain blank. If the user happens to press refresh here, he is shown as logged-in user on the main website. But normally, the user feels that there is some problem with the code and leaves the website.

Thanks for your advise in this matter.

regards

**Comment by ovr** [comment]
Hey! First, question are not related to this repo!

> After that the page remain blank

Looks like after this step, modal should be closed

If I understand your directly it's a popup

Popup/window can be closed automatically by JS, `window.close();`

**Comment by trustinbharat** [comment]
The pop up closes on the normal browser. But in the in-app browser, the Facebook does not actually opens a pop-up. Rather it leaves the home-page of the website and goes to the page where Facebook asks for credentials. After that the user remain there stuck. The issue is only with in-app browser of facebook.

**Comment by ovr** [comment]
Can you share screenshots? I cannot explain what does it mean "in-app browser" of facebook
