### ISSUE TITLE
mt_rand is a linear alg, will be better to provide more true way

### ISSUE THREAD

**Issue by ovr** [SocialConnect/auth#32]
consider using openssl_random_pseudo_bytes() instead.

**Comment by ADmad** [comment]
You can make a method similar [this](https://github.com/cakephp/cakephp/blob/master/src/Utility/Security.php#L100) which tries to use best available function first with fallback to the next best.

**Comment by ovr** [comment]
@ADmad I will review it, thank

**Comment by ovr** [comment]
@ADmad I added, https://github.com/SocialConnect/auth/commit/c5c7c032b8af782926955d064a428f2dd756091f

looks likes I can close this issue, what is your opinion, thank!

**Comment by ADmad** [comment]
Instead of the method existence checks and fallbacks I would suggest just adding `paragonie/random_compat` as dependency which provides `random_bytes()` polyfill.
