### ISSUE TITLE
Facebook can't get access_token

### ISSUE THREAD

**Issue by vitalybaev** [SocialConnect/auth#38]
I've got error when try to get Facebook access_token. I investigated this issue and found, that `parseToken` method of `\SocialConnect\OAuth2\AbstractProvider` is used. That method using `parse_str($body, $token);` function to parse. But I've got json from Facebook.
It could be simple to override this method on Facebook provider class, but I'm not quiet sure that it would be done this way.
Thanks!

Related to #37

**Comment by ovr** [comment]
Thank you 😸 , problem was fixed in `1.2.1` release

You are welcome 🍻
