### ISSUE TITLE
How to store original URL in state 

### ISSUE THREAD

**Issue by blackchineykh** [SocialConnect/auth#46]
Hi, I have successfully implemented this library in my vanilla php website. Thank you so much for your work on this as this has made it easy to implement oauth. However, I am not so familiar with the specc and from reading I noticed there is a 'state' variable that I can use to maintain the original URL of my user before attempting to login. I want to store this URL and then after successful oauth login, redirect the user to this URL. Can you help outline how this can be implemented while using this library?

Thanks for any assistance.

**Comment by ovr** [comment]
Hey!

`state` parameter is useful in preventing CSRF attacks. It's not an url, it's a crypto secure string.

https://github.com/SocialConnect/auth/blob/master/src/OAuth2/AbstractProvider.php#L68

**Comment by ovr** [comment]
I am going to close this issue, but feel free to ask another questions

Thank

**Comment by ovr** [comment]
> I can use to maintain the original URL of my user before attempting to login. I want to store this URL and then after successful oauth login, redirect the user to this URL

Looks like this should be done in your code

You should store $_SERVER['REQUEST_URI'] or $this->request->(uri) in Session

or on pure php:

```php
session_start();
$_SESSION['stored_key_for_url'] = $_SERVER['REQUEST_URI'];
```

And after all try redirect $this->response->redirect or header('Location: ' . $this->session->get('stored_key_for_url')) or similar coder

About redirect/getting url/session you should read in your framework or on php.net

**Comment by blackchineykh** [comment]
Thanks. This works for me
