### ISSUE TITLE
Implement Smashcast provider

### ISSUE THREAD

**Issue by jens1o** [SocialConnect/auth#51]
https://developers.smashcast.tv/#oauth-flow

**Comment by ovr** [comment]
Hey! Are you planning to implement it? (this will be rly awesome) or you request it? Thank

**Comment by jens1o** [comment]
Actually both. I had implemented this on a personal project, so I think I can handle that.

**Comment by ovr** [comment]
Will be rly cool if you submit PR, Thank.

**Comment by jens1o** [comment]
But I have one question. The implementation is very abstract, and their oauth process does not fit in any of these... What should I do?

**Comment by jens1o** [comment]
It fits the best to oauth2.

**Comment by ovr** [comment]
Okey, Just give me time, I will take a look and try to implement it, ~15m

**Comment by jens1o** [comment]
uh, ah, thanks!

**Comment by ovr** [comment]
@jens1o I cannot finish support for it, because they Oauth process is not OAuth and API sucks
I cannot get user without $userId, and the biggest problem I dont known $userId

https://github.com/SocialConnect/auth/pull/52

**Comment by jens1o** [comment]
You can do that, I just replied how it works.

**Comment by ovr** [comment]
@jens1o Thank you bro for your reply, I will try but soon as possible

**Comment by ovr** [comment]
Implemented in `master` and release in `1.4.0` 🍾

**Comment by jens1o** [comment]
wow... Thanks!
