### ISSUE TITLE
Hardcoded return URL

### ISSUE THREAD

**Issue by speller** [SocialConnect/auth#57]
Hello,
Thank you for the great package!
But I have an issue. I use Symfony and want not to use harcoded URLs for auth start and callback methods. In controller I use the `$this->generateUrl('auth_start', ['provider' => 'provider_name'], UrlGeneratorInterface::ABSOLUTE_URL)` and `$this->generateUrl('auth_callback', ['provider' => 'provider_name'], UrlGeneratorInterface::ABSOLUTE_URL)` methods respectively. The issue is that I can not create correct callback URL in this case because library harcodes callback URLs and appends its own provider name to the passed URL. But I should define provider name by myself when generating callback URL and avoid internal URL modification in library. Could you resolve this issue please? For eample, by adding a parameter such as `$appendProviderName = true` to the `AbstractProvider::makeAuthUrl()` method.
Thak you

**Comment by speller** [comment]
If I pass `redirectUri` parameter equals to `http://host/url/` I get the result URL `http://host/url//facebook`. Could you, at least, avoid double slashes on URL generation?

**Comment by ovr** [comment]
Hey! Thank you for bug report, about

> `http://host/url//facebook`

double slash in the case, looks like you specify callback url by `http://..../auth/cb/`

last slash not needed,

> why do you append trailing slash to the redirectUri

I don`t know 😸 

So, I am going to take time and think about this moment

Probably, I will introduce some changes that will help to improve situations with url

Thanks

**Comment by ovr** [comment]
I am implemented a solution to fix this problem, but due an BC break and semver
Fix will be released in `2.0.0`, I will close this issue when `2.0.0` will be released!

refs #b49d906
