### ISSUE TITLE
Enhancement: Add stateless mode.

### ISSUE THREAD

**Issue by ADmad** [SocialConnect/auth#58]
`laravel/socialite` which provides OAuth authentication for laravel has [Stateless Authentication](https://github.com/laravel/socialite#stateless-authentication) mode. Would be nice if `socialconnect/auth` also had such a feature.

**Comment by ovr** [comment]
Hey @ADmad 

I cannot explain why it's rly needed, because state is needed (security reason) for `makeAuthUrl`/`getAccessTokenByRequestParameters`

For `getIdentity` method, it's not needed

Can you provide a case, why it's rly needed =)

Thank

**Comment by ADmad** [comment]
`laravel/socialite`'s readme states "This is useful when adding social authentication to an API".

As per [OAuth2's specs](https://tools.ietf.org/html/rfc6749#section-4.1.1) maintaining state between authorization request and callback is recommended but it's not a must.

So question is whether we want to provide a slightly less secure mode of operation :)

**Comment by ovr** [comment]
@ADmad is it okey if this 'option' will be for each provider as `options`? Thank

**Comment by ADmad** [comment]
Yes :slightly_smiling_face:

**Comment by ovr** [comment]
Implemented and released inside `2.0.0` 😸
