### ISSUE TITLE
help needed in implementing twitter

### ISSUE THREAD

**Issue by anuj9196** [SocialConnect/auth#61]
I have tried this
```
'Twitter' => [
       'enabled' => true,
       'keys' => [
               'key' => '*******',
               'secret' => 'd3DxnqDvh*******************zp1oY******'
        ],
        'includeEmail' => true
],
```

But it is giving error as
```
 Provider response is not success 
Undefined index: applicationId [ROOT/vendor/socialconnect/auth/src/Auth/CollectionFactory.php, line 86]
Undefined index: applicationSecret [ROOT/vendor/socialconnect/auth/src/Auth/CollectionFactory.php, line 86]
```

**Comment by ADmad** [comment]
[This](https://github.com/SocialConnect/auth/blob/master/example/config.php.dist#L16) is what your config array is supposed to look like.

**Comment by anuj9196** [comment]
Thanks a lot.
Do I need to include
```
'includeEmail' => true
```
to get email

**Comment by anuj9196** [comment]
It is giving error
```
Provider response is not success 
SocialConnect\Provider\Exception\InvalidResponse
```

**Comment by ovr** [comment]
@anuj9196 Please take a look at example of the configuration

We don't support any flag like `includeEmail`, it's required by default

![image](https://user-images.githubusercontent.com/572096/32731730-a7887bf2-c89b-11e7-80bb-f78278bd6d22.png)

**Comment by anuj9196** [comment]
that's okay, but what about the `InvalidResponse` Exception `Provider response is not success`?

**Comment by ovr** [comment]
@anuj9196 Sorry for delay, can you provide more information about what response did you get from the Twitter? Thank

If it's secure please send me an email to `talk@dmtry.me`

BTW: I retested, twitter works for me

Thank

**Comment by thapachaki** [comment]
@anuj9196 Perhaps you have "Enable Callback Locking" checked in your Application Settings. Uncheck it.
![captura de pantalla 2018-04-27 a la s 16 33 40](https://user-images.githubusercontent.com/12816865/39384096-a700429e-4a39-11e8-9283-e69cf0a86e41.png)
