### ISSUE TITLE
No public interface to get reponse instance from `InvalidResponse`

### ISSUE THREAD

**Issue by ADmad** [SocialConnect/auth#62]
`SocialConnect\Provider\Exception\InvalidResponse` has the response instance as a protected property. There should be a public method to access the response instance so that it can be used for logging/debugging purposes.

**Comment by ovr** [comment]
@ADmad Hey! Wow, great idea, can you submit PR with this feature?

**Comment by ovr** [comment]
Implemented by @ADmad =)
