### ISSUE TITLE
Cannot connect to Google because of SSL verification error

### ISSUE THREAD

**Issue by ntoka** [SocialConnect/auth#65]
Hi, we are trying to connect login to our service through G+ using this plugin, but we get this SSL verification error:

'fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed fopen(): Failed to enable crypto fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: operation failed'

Everything's installed through composer, so curl should be set up correctly, but this doesn't work for some reason?
Any idea how to fix this? This happens only using Google login - Facebook works fine.

Thanks in advance

**Comment by ovr** [comment]
Hey! Sorry for long delay, what HTTP client do you use?

`\SocialConnect\Common\Http\Client\Curl()` or  `\SocialConnect\Common\Http\Client\Guzzle()`

Thank

**Comment by ADmad** [comment]
He's using my social connect plugin for cakephp. It uses cake's http client which uses sockets. 

His problem is most likely related to outdated openssl lib on the server.  Refs https://github.com/ADmad/cakephp-social-auth/issues/24

**Comment by ovr** [comment]
Thank @ADmad for explanation. I am going to close this issue due an inactivity of @ntoka

@ntoka feel free to ping, thank!
