### ISSUE TITLE
Additional auth url parameters

### ISSUE THREAD

**Issue by highstrike** [SocialConnect/auth#67]
Hello,

Using Google as provider on OAuth2, I have a situation where I would like to restrict the domain of the google account that is signing in and this can be done by adding an additional parameter called `hd`.
 [See here](https://stackoverflow.com/a/11001585/4524447)

Currently, I cannot add custom parameters unless i append them to the string that was generated by `makeAuthUrl()` which seems like a missed opportunity.

I was thinking maybe adding a parameter to that `makeAuthUrl()` function which would be in the form of an array of additional url parameters that would be merged with the default provider parameter array taken from  `getAuthUrlParameters`

OR, **even better**, the additional parameters could be defined in the configuration part for example
```
'provider' => [
    'google' => [
        'parameters' => [
            'hd' => 'domain.tld',
        ],
        'applicationId' => '12345xyz',
        'applicationSecret' => '9876abc',
        'scope' => [
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
        ],
    ],
],
```

Because I am using the cake package provided by @ADmad, changing the `makeAuthUrl()` function would mean updates to his library as well, assuming he would accept them. If the additional parameters are defined in the configuration part then no changes would be needed in any package because it would be native :)

Thanks

**Comment by ovr** [comment]
I am implemented a solution to fix this problem, but this will be released in `2.0.0` 😸 

configuration will be

```php
        'google' => array(
            'applicationId' => '',
            'applicationSecret' => '',
            'scope' => [],
            'options' => [
                'auth.parameters' => [
                    'hd' => 'domain.tld',
                ]
            ]
        ),
```
