### ISSUE TITLE
Feature: Introduce request method inside AbstractProvider

### ISSUE THREAD

**Issue by ovr** [SocialConnect/auth#73]
Hey!

Original request from @ADmad 

>@ovr A feature that would be nice to have in new version of this lib is, being able to get access to the http client used by provider with the accesss token setup. This would allow to easily make additional API requests to the provider.

For e.g. let's say my site allows auth using Facebook and I also want to fetch the friends list of authenticated user. Having access to the http client of Facebook provider would allow me to easily make an API query to fetch friends list without additional effort of crafting a separate http client.

**Comment by jens1o** [comment]
I'd love to take this. :)

**Comment by ovr** [comment]
Will landed in `3.x`
