### ISSUE TITLE
Google Provider class missing in composer.json

### ISSUE THREAD

**Issue by anakrooz** [SocialConnect/auth#8]
Unable to auth with Google because the class is not found, maybe because the link is missing in th composer.json file "autoload":
`"SocialConnect\\Google\\": "providers/Google/"`

Adding it in my own composer.json "autoload" (with full path) make it work:
```
"autoload": {
        "psr-4": {
            "SocialConnect\\Google\\": "vendor/socialconnect/auth/providers/Google/"
        }
    }
```

**Comment by layershifter** [comment]
@anakrooz, it's my miss. I made PR that fixes this issue.

ping @ovr

**Comment by ovr** [comment]
Seems It's fixed

Thanks @layershifter 👍
