### ISSUE TITLE
Facebook empty email

### ISSUE THREAD

**Issue by ldim87** [SocialConnect/auth#81]
Hi, I don't know if it is a library issue, but facebook returns null email even if permissions are set.

**Comment by denkurbatov** [comment]
@ldim87 Are you sure that user has email? Facebook allows users to register by phone number.

**Comment by ldim87** [comment]
It is my user and I have email for sure (in fact I have two - one primary and one secondary)... maybe it is a facebook bug of some sort... In php script when I do:

$user = $provider->getIdentity($accessToken);
var_dump ($user);

output is:
object(SocialConnect\Common\Entity\User)#19 (10) { ["id"]=> string(17) "xxxxx" ["firstname"]=> NULL ["lastname"]=> NULL ["email"]=> NULL ["emailVerified"]=> bool(true) ["birthday"]=> NULL ["username"]=> NULL ["sex"]=> NULL ["fullname"]=> string(10) "xxxxx" ["pictureURL"]=> NULL }

**Comment by ovr** [comment]
@ldim87 did you configure `facebook` provider with?

```
            'options' => [
                'identity.fields' => [
                    'email',
                ],
            ]
```

Example https://github.com/SocialConnect/auth/blob/master/example/config.php.dist#L15

Thanks

**Comment by ldim87** [comment]
Yes, that's it... Thanks. I think you should update the README.md

**Comment by ovr** [comment]
> Thanks. I think you should update the README.md

Nice Catch 👍
