### ISSUE TITLE
Twitter Unknown authorization

### ISSUE THREAD

**Issue by cherimo** [SocialConnect/auth#83]
Dear,

When I click on the Twitter option within my application it generates an Auth. Link to redirect. When I use that link to login everything is fine I get data etc... 
But when I curl the same page with Post option(Provider) I get also a Auth. Link to redirect but when i go the link I end up with "Unknown authorization" I use Instagram, Linkedin and Facebook and that all works fine. Except Twitter. What am I doing wrong?

**Comment by ovr** [comment]
Hey! Sorry for late reply..

`UnknownAuthorization` is an error when there is no `oauth1_request_token` inside session

Standart session adapter use native/plain PHP sessions, you should take a look in your applications

I am going to close this issue, feel free to ask questions here

Thanks
