### ISSUE TITLE
Linkedin "API response with error code"

### ISSUE THREAD

**Issue by githubov** [SocialConnect/auth#97]
![Screenshot_3](https://user-images.githubusercontent.com/55645208/66773907-fbbc8880-eee1-11e9-9953-982bb06f6065.png)

facebook twitter working but problem with linkedin :(

**Comment by githubov** [comment]
linkedin authentication success but when try to fetch user info like name, picture not working show error.

**Comment by githubov** [comment]
`		'linkedin'  => [
			'applicationId'     => '81******cj**9t',
			'applicationSecret' => 'zxE*****M4**sU',
			'scope'             => array('r_liteprofile', 'r_emailaddress')
		],`

**Comment by ovr** [comment]
@githubov what version are you using?

**Comment by ovr** [comment]
I review this on my local machine and found that LinkedIn drop `v1` API

I've prepared a new patch release `3.0.1` with fixes for it
Related to 1.x/2.x branch, probably I need a help with back porting it

Thanks

**Comment by githubov** [comment]
THANK YOU **OVR** Working Now :)
